/**
 * Hostinger Optimized Entry Point
 * 
 * This file wraps the Next.js standalone server to enforce resource limits
 * required for stable operation on Hostinger shared hosting environments.
 */

// Force the Node.js thread pool to stay at 1.
// This is the most critical setting to prevent 503 errors on Hostinger.
process.env.UV_THREADPOOL_SIZE = '1';

// Disable Next.js telemetry at runtime to save memory and network overhead.
process.env.NEXT_TELEMETRY_DISABLED = '1';

// Ensure the port is set (Hostinger usually uses 3000 by default, but we'll be explicit)
process.env.PORT = process.env.PORT || '3000';

// Set production environment
process.env.NODE_ENV = 'production';

console.log('--- Starting Production Server (Hostinger Mode) ---');
console.log('Resource Limits: UV_THREADPOOL_SIZE = 1');

// Load the standalone server generated by 'next build'
try {
  require('./.next/standalone/server.js');
} catch (error) {
  console.error('FAILED TO START NEXT.JS STANDALONE SERVER');
  console.error('Make sure you have run "npm run build" before starting.');
  console.error(error);
  process.exit(1);
}
